export const showElement = element => (element.style.display = 'inline');
export const hideElement = element => (element.style.display = 'none');
export const $ = document.querySelector.bind(document);
export const $c = document.createElement.bind(document);
export const $rAF = window.requestAnimationFrame.bind(window);
export const $sT = window.setTimeout.bind(window);
export const $cT = window.clearTimeout.bind(window);
export const $sI = window.setInterval.bind(window);
export const $cI = window.clearInterval.bind(window);
export const $aEL = window.addEventListener.bind(window);
export const $rEL = window.removeEventListener.bind(window);
export const $r = Math.random.bind(Math);
